package com.oldagehome.portal.pdf;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import com.oldagehome.portal.inventory.Inventory;

import java.io.ByteArrayOutputStream;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;

public class InventoryReportGenerator {

    public static byte[] generatePdf(List<Inventory> items, String title, String generatedBy) {
        Document document = new Document(PageSize.A4, 36, 36, 54, 36);
        ByteArrayOutputStream out = new ByteArrayOutputStream();

        try {
            PdfWriter writer = PdfWriter.getInstance(document, out);
            writer.setPageEvent(new PdfPageEventHelper() {
                @Override
                public void onEndPage(PdfWriter writer, Document document) {
                    PdfContentByte cb = writer.getDirectContent();
                    Font footerFont = FontFactory.getFont(FontFactory.HELVETICA, 8, Font.NORMAL, BaseColor.GRAY);
                    ColumnText.showTextAligned(cb, Element.ALIGN_RIGHT,
                        new Phrase("Smart Old Age Home System", footerFont),
                        document.right(), document.top() + 10, 0);

                    ColumnText.showTextAligned(cb, Element.ALIGN_CENTER,
                        new Phrase("Page " + writer.getPageNumber(), footerFont),
                        (document.left() + document.right()) / 2, document.bottom() - 15, 0);
                }
            });

            document.open();

            Font subTitleFont = FontFactory.getFont(FontFactory.HELVETICA, 10, Font.ITALIC, BaseColor.GRAY);
            Font metaFont = FontFactory.getFont(FontFactory.HELVETICA, 9, Font.NORMAL, BaseColor.DARK_GRAY);

            Paragraph header = new Paragraph("SMART OLD AGE HOME", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 22, new BaseColor(37, 99, 235)));
            header.setAlignment(Element.ALIGN_CENTER);
            document.add(header);

            Paragraph subtitle = new Paragraph("Reports & Analytics Portal", subTitleFont);
            subtitle.setAlignment(Element.ALIGN_CENTER);
            subtitle.setSpacingAfter(15);
            document.add(subtitle);

            Paragraph details = new Paragraph();
            details.setFont(metaFont);
            details.add("Report Name: " + title + "\n");
            details.add("Generated On: " + LocalDate.now().format(DateTimeFormatter.ofPattern("dd-MM-yyyy")) + "\n");
            details.add("Generated By: " + generatedBy + "\n");
            details.setSpacingAfter(20);
            document.add(details);

            PdfPTable table = new PdfPTable(7);
            table.setWidthPercentage(100);
            table.setWidths(new float[]{1.5f, 2.5f, 1.8f, 1.2f, 1.5f, 1.8f, 1.8f});

            String[] headers = {"Code", "Name", "Category", "Qty", "Price (₹)", "Expiry", "Status"};
            Font headerCellFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10, BaseColor.WHITE);
            for (String h : headers) {
                PdfPCell cell = new PdfPCell(new Phrase(h, headerCellFont));
                cell.setBackgroundColor(new BaseColor(37, 99, 235));
                cell.setPadding(6);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(cell);
            }

            Font rowFont = FontFactory.getFont(FontFactory.HELVETICA, 9, BaseColor.BLACK);
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
            for (Inventory item : items) {
                table.addCell(new PdfPCell(new Phrase(item.getMedicineCode(), rowFont)));
                table.addCell(new PdfPCell(new Phrase(item.getMedicineName(), rowFont)));
                table.addCell(new PdfPCell(new Phrase(item.getCategory() != null ? item.getCategory().name() : "", rowFont)));
                table.addCell(new PdfPCell(new Phrase(String.valueOf(item.getQuantity()), rowFont)));
                table.addCell(new PdfPCell(new Phrase(item.getUnitPrice() != null ? "₹" + item.getUnitPrice().toString() : "-", rowFont)));
                table.addCell(new PdfPCell(new Phrase(item.getExpiryDate() != null ? item.getExpiryDate().format(formatter) : "-", rowFont)));
                
                PdfPCell statusCell = new PdfPCell(new Phrase(item.getStatus() != null ? item.getStatus().name() : "", rowFont));
                statusCell.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(statusCell);
            }

            document.add(table);

            Paragraph summary = new Paragraph();
            summary.setFont(metaFont);
            summary.setSpacingBefore(15);
            summary.add("Total Items Count: " + items.size() + "\n");
            document.add(summary);

            document.close();
        } catch (DocumentException e) {
            e.printStackTrace();
        }

        return out.toByteArray();
    }
}
