package com.oldagehome.portal.pdf;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import com.oldagehome.portal.resident.Resident;

import java.io.ByteArrayOutputStream;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;

public class ResidentReportGenerator {

    public static byte[] generatePdf(List<Resident> residents, String title, String generatedBy) {
        Document document = new Document(PageSize.A4, 36, 36, 54, 36);
        ByteArrayOutputStream out = new ByteArrayOutputStream();

        try {
            PdfWriter writer = PdfWriter.getInstance(document, out);
            // Footer helper for Page Numbers & Generation Details
            writer.setPageEvent(new PdfPageEventHelper() {
                @Override
                public void onEndPage(PdfWriter writer, Document document) {
                    PdfContentByte cb = writer.getDirectContent();
                    Font footerFont = FontFactory.getFont(FontFactory.HELVETICA, 8, Font.NORMAL, BaseColor.GRAY);
                    
                    // Header
                    ColumnText.showTextAligned(cb, Element.ALIGN_RIGHT,
                        new Phrase("Smart Old Age Home System", footerFont),
                        document.right(), document.top() + 10, 0);

                    // Footer
                    ColumnText.showTextAligned(cb, Element.ALIGN_CENTER,
                        new Phrase("Page " + writer.getPageNumber(), footerFont),
                        (document.left() + document.right()) / 2, document.bottom() - 15, 0);
                }
            });

            document.open();

            // Document Header
            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18, BaseColor.DARK_GRAY);
            Font subTitleFont = FontFactory.getFont(FontFactory.HELVETICA, 10, Font.ITALIC, BaseColor.GRAY);
            Font metaFont = FontFactory.getFont(FontFactory.HELVETICA, 9, Font.NORMAL, BaseColor.DARK_GRAY);

            Paragraph header = new Paragraph("SMART OLD AGE HOME", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 22, new BaseColor(37, 99, 235)));
            header.setAlignment(Element.ALIGN_CENTER);
            document.add(header);

            Paragraph subtitle = new Paragraph("Reports & Analytics Portal", subTitleFont);
            subtitle.setAlignment(Element.ALIGN_CENTER);
            subtitle.setSpacingAfter(15);
            document.add(subtitle);

            // Report Details Line
            Paragraph details = new Paragraph();
            details.setFont(metaFont);
            details.add("Report Name: " + title + "\n");
            details.add("Generated On: " + LocalDate.now().format(DateTimeFormatter.ofPattern("dd-MM-yyyy")) + "\n");
            details.add("Generated By: " + generatedBy + "\n");
            details.setSpacingAfter(20);
            document.add(details);

            // Add Table
            PdfPTable table = new PdfPTable(6);
            table.setWidthPercentage(100);
            table.setWidths(new float[]{2.5f, 1.2f, 1f, 1.8f, 1.8f, 1.5f});

            // Headers
            String[] headers = {"Name", "Gender", "Age", "Mobile", "Joining Date", "Status"};
            Font headerCellFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10, BaseColor.WHITE);
            for (String h : headers) {
                PdfPCell cell = new PdfPCell(new Phrase(h, headerCellFont));
                cell.setBackgroundColor(new BaseColor(37, 99, 235));
                cell.setPadding(6);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(cell);
            }

            // Data rows
            Font rowFont = FontFactory.getFont(FontFactory.HELVETICA, 9, BaseColor.BLACK);
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
            for (Resident r : residents) {
                table.addCell(new PdfPCell(new Phrase(r.getFullName(), rowFont)));
                table.addCell(new PdfPCell(new Phrase(r.getGender(), rowFont)));
                table.addCell(new PdfPCell(new Phrase(String.valueOf(r.getAge() != null ? r.getAge() : ""), rowFont)));
                table.addCell(new PdfPCell(new Phrase(r.getMobile() != null ? r.getMobile() : "-", rowFont)));
                table.addCell(new PdfPCell(new Phrase(r.getJoiningDate() != null ? r.getJoiningDate().format(formatter) : "-", rowFont)));
                
                PdfPCell statusCell = new PdfPCell(new Phrase(r.getStatus() != null ? r.getStatus().name() : "", rowFont));
                statusCell.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(statusCell);
            }

            document.add(table);

            // Summary Section
            Paragraph summary = new Paragraph();
            summary.setFont(metaFont);
            summary.setSpacingBefore(15);
            summary.add("Total Residents Count: " + residents.size() + "\n");
            document.add(summary);

            document.close();
        } catch (DocumentException e) {
            e.printStackTrace();
        }

        return out.toByteArray();
    }
}
